const rndServices = angular.module('rndServices', []);

rndServices.service('rndServices', function () {
  const services = {};

  //Countries' data
  // add country codes from this list:
  // http://www.nationsonline.org/oneworld/country_code_list.htm
  const flagClass = 'flag-icon flag-icon-';

  services.timeline = [
    {
      city: 'Marrakesh',
      country: 'MA',
      dateVisited: 'May 2019',
      latitude: 31.6294723,
      longitude: -7.981084500000001,
      id: 'MA',
      showAsSelected: true,
      name: 'Morocco',
      year: 2019,
      countryCode: 'flag-icon flag-icon-MA'
    },
    {
      city: 'Marrakesh',
      country: 'MA',
      dateVisited: 'May 2019',
      latitude: 31.6294723,
      longitude: -7.981084500000001,
      id: 'MA',
      showAsSelected: true,
      name: 'Morocco',
      year: 2019,
      countryCode: 'flag-icon flag-icon-MA'
    },
    {
      city: 'Essaouira',
      country: 'MA',
      dateVisited: 'May 2019',
      latitude: 31.5084926,
      longitude: -9.7595041,
      id: 'MA',
      showAsSelected: true,
      name: 'Morocco',
      year: 2019,
      countryCode: 'flag-icon flag-icon-MA'
    },
    {
      city: 'Sarajevo',
      country: 'BA',
      dateVisited: 'Aug 2019',
      latitude: 43.8562586,
      longitude: 18.4130763,
      id: 'BA',
      showAsSelected: true,
      name: 'Bosnia and Herzegovina',
      year: 2019,
      countryCode: 'flag-icon flag-icon-BA'
    },
    {
      city: 'Mostar',
      country: 'BA',
      dateVisited: 'Aug 2019',
      latitude: 43.34377480000001,
      longitude: 17.8077578,
      id: 'BA',
      showAsSelected: true,
      name: 'Bosnia and Herzegovina',
      year: 2019,
      countryCode: 'flag-icon flag-icon-BA'
    },
    {
      city: 'Dubrovnik',
      country: 'HR',
      dateVisited: 'Aug 2019',
      latitude: 42.65066059999999,
      longitude: 18.0944238,
      id: 'HR',
      showAsSelected: true,
      name: 'Croatia',
      year: 2019,
      countryCode: 'flag-icon flag-icon-HR'
    },
    {
      city: 'Vienna',
      country: 'AT',
      dateVisited: 'Aug 2019',
      latitude: 48.2081743,
      longitude: 16.3738189,
      id: 'AT',
      showAsSelected: true,
      name: 'Austria',
      year: 2019,
      countryCode: 'flag-icon flag-icon-AT'
    },
    {
      city: 'Cape Town',
      country: 'ZA',
      dateVisited: 'Sep 2019',
      latitude: -33.9248685,
      longitude: 18.4240553,
      id: 'ZA',
      showAsSelected: true,
      name: 'South Africa',
      year: 2019,
      countryCode: 'flag-icon flag-icon-ZA'
    },
    {
      city: 'Manyeleti',
      country: 'ZA',
      dateVisited: 'Nov 2019',
      latitude: -24.6479532,
      longitude: 31.5262986,
      id: 'ZA',
      showAsSelected: true,
      name: 'South Africa',
      year: 2019,
      countryCode: 'flag-icon flag-icon-ZA'
    },
    {
      city: 'Cape Town',
      country: 'ZA',
      dateVisited: 'Nov 2019',
      latitude: -33.9248685,
      longitude: 18.4240553,
      id: 'ZA',
      showAsSelected: true,
      name: 'South Africa',
      year: 2019,
      countryCode: 'flag-icon flag-icon-ZA'
    },
    {
      city: 'Honk Kong',
      country: 'HK',
      dateVisited: 'Dec 2019',
      latitude: 22.3193039,
      longitude: 114.1693611,
      id: 'HK',
      showAsSelected: true,
      name: 'Hong Kong',
      year: 2019,
      countryCode: 'flag-icon flag-icon-HK'
    },
    {
      city: 'Los Angeles',
      country: 'US',
      dateVisited: 'Dec 2019',
      latitude: 34.0522342,
      longitude: -118.2436849,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: 2019,
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Sixmilebridge',
      country: 'IE',
      dateVisited: 'Dec 2019',
      latitude: 52.7436246,
      longitude: -8.777650399999999,
      id: 'IE',
      showAsSelected: true,
      name: 'Ireland',
      year: 2019,
      countryCode: 'flag-icon flag-icon-IE'
    },
    {
      city: 'Dublin',
      country: 'IE',
      dateVisited: 'Jan 2020',
      latitude: 53.3498053,
      longitude: -6.2603097,
      id: 'IE',
      showAsSelected: true,
      name: 'Ireland',
      year: 2020,
      countryCode: 'flag-icon flag-icon-IE'
    },
    {
      city: 'Rome',
      country: 'IT',
      dateVisited: 'Jan 2020',
      latitude: 41.9027835,
      longitude: 12.4963655,
      id: 'IT',
      showAsSelected: true,
      name: 'Italy',
      year: '2020',
      countryCode: 'flag-icon flag-icon-IT'
    },
    {
      city: 'Florence',
      country: 'IT',
      dateVisited: 'Feb 2020',
      latitude: 43.7695604,
      longitude: 11.2558136,
      id: 'IT',
      showAsSelected: true,
      name: 'Italy',
      year: '2020',
      countryCode: 'flag-icon flag-icon-IT'
    },
    {
      city: 'Milan',
      country: 'IT',
      dateVisited: 'Feb 2020',
      latitude: 45.4642035,
      longitude: 9.189982,
      id: 'IT',
      showAsSelected: true,
      name: 'Italy',
      year: '2020',
      countryCode: 'flag-icon flag-icon-IT'
    },
    {
      city: "T'bilisi",
      country: 'GE',
      dateVisited: 'Mar 2020',
      latitude: 41.7151377,
      longitude: 44.827096,
      id: 'GE',
      showAsSelected: true,
      name: 'Georgia',
      year: '2020',
      countryCode: 'flag-icon flag-icon-GE'
    },
    {
      city: 'Los Angeles',
      country: 'US',
      dateVisited: 'Apr 2020',
      latitude: 34.0522342,
      longitude: -118.2436849,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2020',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Mexico City',
      country: 'MX',
      dateVisited: 'Oct 2020',
      latitude: 19.4326077,
      longitude: -99.133208,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2020',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Oaxaca',
      country: 'MX',
      dateVisited: 'Jan 2021',
      latitude: 17.0731842,
      longitude: -96.7265889,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2021',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Playa del Carmen',
      country: 'MX',
      dateVisited: 'Feb 2021',
      latitude: 20.6295586,
      longitude: -87.0738851,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2021',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Tulum',
      country: 'MX',
      dateVisited: 'Feb 2021',
      latitude: 20.2114,
      longitude: -87.4654,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2021',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Merida',
      country: 'MX',
      dateVisited: 'Mar 2021',
      latitude: 20.9673702,
      longitude: -89.5925857,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2021',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Mexico City',
      country: 'MX',
      dateVisited: 'Apr 2021',
      latitude: 19.4326077,
      longitude: -99.133208,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2021',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'St. Louis',
      country: 'US',
      dateVisited: 'Jun 2021',
      latitude: 38.6270025,
      longitude: -90.19940419999999,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2021',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Fredericktown',
      country: 'US',
      dateVisited: 'June 2021',
      latitude: 37.55977540000001,
      longitude: -90.2940069,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2021',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Portland',
      country: 'US',
      dateVisited: 'Jul 2021',
      latitude: 45.5051064,
      longitude: -122.6750261,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2021',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Eugene',
      country: 'US',
      dateVisited: 'Jul 2021',
      latitude: 44.0520691,
      longitude: -123.0867536,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: 2021,
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Dundee',
      country: 'US',
      dateVisited: 'Jul 2021',
      latitude: 45.278395,
      longitude: -123.0146524,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: 2021,
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Seattle',
      country: 'US',
      dateVisited: 'Jul 2021',
      latitude: 47.6062095,
      longitude: -122.3320708,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2021',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Nashville',
      country: 'US',
      dateVisited: 'Aug 2021',
      latitude: 36.1622296,
      longitude: -86.7743531,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: 2022,
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Amsterdam',
      country: 'NL',
      dateVisited: 'Aug 2021',
      latitude: 52.3702157,
      longitude: 4.895167900000001,
      id: 'NL',
      showAsSelected: true,
      name: 'Netherlands',
      year: '2021',
      countryCode: 'flag-icon flag-icon-NL'
    },
    {
      city: 'Delft',
      country: 'NL',
      dateVisited: 'Aug 2021',
      latitude: 52.01157689999999,
      longitude: 4.3570677,
      id: 'NL',
      showAsSelected: true,
      name: 'Netherlands',
      year: '2021',
      countryCode: 'flag-icon flag-icon-NL'
    },
    {
      city: 'Budapest',
      country: 'HU',
      dateVisited: 'Aug 2021',
      latitude: 47.497912,
      longitude: 19.040235,
      id: 'HU',
      showAsSelected: true,
      name: 'Hungary',
      year: '2021',
      countryCode: 'flag-icon flag-icon-HU'
    },
    {
      city: 'Porto',
      country: 'PT',
      dateVisited: 'Sep 2021',
      latitude: 41.1579438,
      longitude: -8.629105299999999,
      id: 'PT',
      showAsSelected: true,
      name: 'Portugal',
      year: '2021',
      countryCode: 'flag-icon flag-icon-PT'
    },
    {
      city: 'Douro Valley',
      country: 'PT',
      dateVisited: 'Oct 2021',
      latitude: 41.17133889999999,
      longitude: -7.802805800000001,
      id: 'PT',
      showAsSelected: true,
      name: 'Portugal',
      year: '2021',
      countryCode: 'flag-icon flag-icon-PT'
    },
    {
      city: 'Cape Town',
      country: 'ZA',
      dateVisited: 'Oct 2021',
      latitude: -33.9248685,
      longitude: 18.4240553,
      id: 'ZA',
      showAsSelected: true,
      name: 'South Africa',
      year: 2021,
      countryCode: 'flag-icon flag-icon-ZA'
    },
    {
      city: 'Cederberg',
      country: 'ZA',
      dateVisited: 'Dec 2021',
      latitude: -32.5891202,
      longitude: 19.0118251,
      id: 'ZA',
      showAsSelected: true,
      name: 'South Africa',
      year: '2021',
      countryCode: 'flag-icon flag-icon-ZA'
    },
    {
      city: 'Kogelberg',
      country: 'ZA',
      dateVisited: 'Feb 2022',
      latitude: -34.3321752,
      longitude: 18.9877857,
      id: 'ZA',
      showAsSelected: true,
      name: 'South Africa',
      year: '2022',
      countryCode: 'flag-icon flag-icon-ZA'
    },
    {
      city: 'Windhoek',
      country: 'NA',
      dateVisited: 'Apr 2022',
      latitude: -22.5608807,
      longitude: 17.0657549,
      id: 'NA',
      showAsSelected: true,
      name: 'Namibia',
      year: '2022',
      countryCode: 'flag-icon flag-icon-NA'
    },
    {
      city: 'Hoanib Valley',
      country: 'NA',
      dateVisited: 'Apr 2022',
      latitude: -19.26889495039575,
      longitude: 13.29075839237384,
      id: 'NA',
      showAsSelected: true,
      name: 'Namibia',
      year: '2022',
      countryCode: 'flag-icon flag-icon-NA'
    },
    {
      city: 'Etosha',
      country: 'NA',
      dateVisited: 'Apr 2022',
      latitude: -18.8555909,
      longitude: 16.3293197,
      id: 'NA',
      showAsSelected: true,
      name: 'Namibia',
      year: '2022',
      countryCode: 'flag-icon flag-icon-NA'
    },
    {
      city: 'Sossusvlei',
      country: 'NA',
      dateVisited: 'Apr 2022',
      latitude: -24.7273906,
      longitude: 15.3423909,
      id: 'NA',
      showAsSelected: true,
      name: 'Namibia',
      year: '2022',
      countryCode: 'flag-icon flag-icon-NA'
    },
    {
      city: 'Kigali',
      country: 'RW',
      dateVisited: 'May 2022',
      latitude: -1.9440727,
      longitude: 30.0618851,
      id: 'RW',
      showAsSelected: true,
      name: 'Rwanda',
      year: '2022',
      countryCode: 'flag-icon flag-icon-RW'
    },
    {
      city: 'Bugambira',
      country: 'UG',
      dateVisited: 'May 2022',
      latitude: -1.116667,
      longitude: 29.7,
      id: 'UG',
      showAsSelected: true,
      name: 'Uganda',
      year: '2022',
      countryCode: 'flag-icon flag-icon-UG'
    },
    {
      city: 'Cairo',
      country: 'EG',
      dateVisited: 'Jun 2022',
      latitude: 30.0444196,
      longitude: 31.2357116,
      id: 'EG',
      showAsSelected: true,
      name: 'Egypt',
      year: '2022',
      countryCode: 'flag-icon flag-icon-EG'
    },
    {
      city: 'Madrid',
      country: 'ES',
      dateVisited: 'Jun 2022',
      latitude: 40.4167754,
      longitude: -3.7037902,
      id: 'ES',
      showAsSelected: true,
      name: 'Spain',
      year: '2022',
      countryCode: 'flag-icon flag-icon-ES'
    },
    {
      city: 'Granada',
      country: 'ES',
      dateVisited: 'Jun 2022',
      latitude: 37.1773363,
      longitude: -3.5985571,
      id: 'ES',
      showAsSelected: true,
      name: 'Spain',
      year: '2022',
      countryCode: 'flag-icon flag-icon-ES'
    },
    {
      city: 'Gerano',
      country: 'IT',
      dateVisited: 'Jun 2022',
      latitude: 41.93372189999999,
      longitude: 12.9934362,
      id: 'IT',
      showAsSelected: true,
      name: 'Italy',
      year: '2022',
      countryCode: 'flag-icon flag-icon-IT'
    },
    {
      city: 'Naples',
      country: 'IT',
      dateVisited: 'Jul 2022',
      latitude: 40.8517983,
      longitude: 14.26812,
      id: 'IT',
      showAsSelected: true,
      name: 'Italy',
      year: '2022',
      countryCode: 'flag-icon flag-icon-IT'
    },
    {
      city: 'Prague',
      country: 'CZ',
      dateVisited: 'Jul 2022',
      latitude: 50.0755381,
      longitude: 14.4378005,
      id: 'CZ',
      showAsSelected: true,
      name: 'Czech Republic',
      year: '2022',
      countryCode: 'flag-icon flag-icon-CZ'
    },
    {
      city: 'Barcelona',
      country: 'ES',
      dateVisited: 'Aug 2022',
      latitude: 41.3851,
      longitude: 2.1734,
      id: 'ES',
      showAsSelected: true,
      name: 'Spain',
      year: '2022',
      countryCode: 'flag-icon flag-icon-ES'
    },
    {
      city: 'Mexico City',
      country: 'MX',
      dateVisited: 'Aug 2022',
      latitude: 19.4326077,
      longitude: -99.133208,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2022',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Santa Rosa',
      country: 'US',
      dateVisited: 'Oct 2022',
      latitude: 38.4404,
      longitude: -122.7141,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2022',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Seattle',
      country: 'US',
      dateVisited: 'Oct 2022',
      latitude: 47.6062095,
      longitude: -122.3320708,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2022',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Mexico City',
      country: 'MX',
      dateVisited: 'Oct 2022',
      latitude: 19.4326077,
      longitude: -99.133208,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2022',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Mixquic',
      country: 'MX',
      dateVisited: 'Nov 2022',
      latitude: 19.2266531,
      longitude: -98.9659399,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2022',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Puebla',
      country: 'MX',
      dateVisited: 'Nov 2022',
      latitude: 19.0414398,
      longitude: -98.2062727,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2022',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Fredericktown',
      country: 'US',
      dateVisited: 'Dec 2022',
      latitude: 37.55977540000001,
      longitude: -90.2940069,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2022',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Vancouver',
      country: 'CA',
      dateVisited: 'Dec 2022',
      latitude: 49.2827291,
      longitude: -123.1207375,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2022',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Victoria',
      country: 'CA',
      dateVisited: 'Jan 2023',
      latitude: 48.4284,
      longitude: -123.3656,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Calgary',
      country: 'CA',
      dateVisited: 'Feb 2023',
      latitude: 51.04473309999999,
      longitude: -114.0718831,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Lake Louise',
      country: 'CA',
      dateVisited: 'Feb 2023',
      latitude: 51.4253705,
      longitude: -116.1772552,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Drumheller',
      country: 'CA',
      dateVisited: 'Feb 2023',
      latitude: 51.4645,
      longitude: -112.7108,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Toronto',
      country: 'CA',
      dateVisited: 'Mar 2023',
      latitude: 43.653226,
      longitude: -79.3831843,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Montreal',
      country: 'CA',
      dateVisited: 'Apr 2023',
      latitude: 45.5018869,
      longitude: -73.56739189999999,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'St. Louis',
      country: 'US',
      dateVisited: 'Apr 2023',
      latitude: 38.6270025,
      longitude: -90.19940419999999,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2023',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Bogota',
      country: 'CO',
      dateVisited: 'May 2023',
      latitude: 4.710988599999999,
      longitude: -74.072092,
      id: 'CO',
      showAsSelected: true,
      name: 'Colombia',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CO'
    },
    {
      city: 'Cartagena',
      country: 'CO',
      dateVisited: 'May 2023',
      latitude: 10.3910485,
      longitude: -75.4794257,
      id: 'CO',
      showAsSelected: true,
      name: 'Colombia',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CO'
    },
    {
      city: 'Zipaquira',
      country: 'CO',
      dateVisited: 'Jun 2023',
      latitude: 5.021476,
      longitude: -73.990955,
      id: 'CO',
      showAsSelected: true,
      name: 'Colombia',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CO'
    },
    {
      city: 'Buenos Aires',
      country: 'AR',
      dateVisited: 'Jun 2023',
      latitude: -34.6036844,
      longitude: -58.3815591,
      id: 'AR',
      showAsSelected: true,
      name: 'Argentina',
      year: '2023',
      countryCode: 'flag-icon flag-icon-AR'
    },
    {
      city: 'El Calafate',
      country: 'AR',
      dateVisited: 'Jul 2023',
      latitude: -50.337969,
      longitude: -72.2647981,
      id: 'AR',
      showAsSelected: true,
      name: 'Argentina',
      year: '2023',
      countryCode: 'flag-icon flag-icon-AR'
    },
    {
      city: 'Buenos Aires',
      country: 'AR',
      dateVisited: 'Jul 2023',
      latitude: -34.6036844,
      longitude: -58.3815591,
      id: 'AR',
      showAsSelected: true,
      name: 'Argentina',
      year: '2023',
      countryCode: 'flag-icon flag-icon-AR'
    },
    {
      city: 'Mendoza',
      country: 'AR',
      dateVisited: 'Aug 2023',
      latitude: -32.8894587,
      longitude: -68.8458386,
      id: 'AR',
      showAsSelected: true,
      name: 'Argentina',
      year: '2023',
      countryCode: 'flag-icon flag-icon-AR'
    },
    {
      city: 'Buenos Aires',
      country: 'AR',
      dateVisited: 'Aug 2023',
      latitude: -34.6036844,
      longitude: -58.3815591,
      id: 'AR',
      showAsSelected: true,
      name: 'Argentina',
      year: '2023',
      countryCode: 'flag-icon flag-icon-AR'
    },
    {
      city: 'Quito',
      country: 'EC',
      dateVisited: 'Aug 2023',
      latitude: -0.1806532,
      longitude: -78.4678382,
      id: 'EC',
      showAsSelected: true,
      name: 'Ecuador',
      year: '2023',
      countryCode: 'flag-icon flag-icon-EC'
    },
    {
      city: 'Lake Pilchicocha',
      country: 'EC',
      dateVisited: 'Aug 2023',
      latitude: -0.472445,
      longitude: -76.458844,
      id: 'EC',
      showAsSelected: true,
      name: 'Ecuador',
      year: '2023',
      countryCode: 'flag-icon flag-icon-EC'
    },
    {
      city: 'Galapagos Islands',
      country: 'EC',
      dateVisited: 'Aug 2023',
      latitude: -0.3831059167914707,
      longitude: -90.42333442620028,
      id: 'EC',
      showAsSelected: true,
      name: 'Ecuador',
      year: '2023',
      countryCode: 'flag-icon flag-icon-EC'
    },
    {
      city: 'Quito',
      country: 'EC',
      dateVisited: 'Sep 2023',
      latitude: -0.1806532,
      longitude: -78.4678382,
      id: 'EC',
      showAsSelected: true,
      name: 'Ecuador',
      year: '2023',
      countryCode: 'flag-icon flag-icon-EC'
    },
    {
      city: 'Toronto',
      country: 'CA',
      dateVisited: 'Sep 2023',
      latitude: 43.653226,
      longitude: -79.3831843,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'St. Louis',
      country: 'US',
      dateVisited: 'Sep 2023',
      latitude: 38.6270025,
      longitude: -90.19940419999999,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2023',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'Toronto',
      country: 'CA',
      dateVisited: 'Sep 2023',
      latitude: 43.653226,
      longitude: -79.3831843,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Toronto',
      country: 'CA',
      dateVisited: 'Sep 2023',
      latitude: 43.653226,
      longitude: -79.3831843,
      id: 'CA',
      showAsSelected: true,
      name: 'Canada',
      year: '2023',
      countryCode: 'flag-icon flag-icon-CA'
    },
    {
      city: 'Mexico City',
      country: 'MX',
      dateVisited: 'Nov 2023',
      latitude: 19.4326077,
      longitude: -99.133208,
      id: 'MX',
      showAsSelected: true,
      name: 'Mexico',
      year: '2023',
      countryCode: 'flag-icon flag-icon-MX'
    },
    {
      city: 'Austin',
      country: 'US',
      dateVisited: 'Jan 2024',
      latitude: 30.25,
      longitude: -97.75,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2024',
      countryCode: 'flag-icon flag-icon-US'
    },
    {
      city: 'St. Louis',
      country: 'US',
      dateVisited: 'Jan 2024',
      latitude: 38.6270025,
      longitude: -90.19940419999999,
      id: 'US',
      showAsSelected: true,
      name: 'United States',
      year: '2024',
      countryCode: 'flag-icon flag-icon-US'
    }
  ];

  //Countries' data
  // add country codes from this list:
  // http://www.nationsonline.org/oneworld/country_code_list.htm

  return services;
});
